# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  # 부트 로더 (rEFInd가 찾을 수 있도록 최소한으로 설정)
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;
  boot.loader.efi.efiSysMountPoint = "/boot";

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usbhid" "uas" "sd_mod" ];
  boot.initrd.kernelModules = [ ];

  boot.kernelPackages = pkgs.linuxPackages;
  boot.kernelModules = [ "kvm-amd" ];

  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/a6b6e62e-127c-4000-977a-5133ab4f03a6";
      fsType = "btrfs";
      options = [
        "subvol=@"
        "compress=zstd:3" # 압축 수준 3 (성능과 압축률의 최적 지점)
        "noatime"         # 파일 읽을 때마다 시간을 기록하지 않음 (SSD 성능 향상)
        "discard=async"   # 백그라운드에서 TRIM 실행 (Linux 5.6+ 권장)
        "space_cache=v2"  # 최신 공간 캐시 알고리즘
      ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/a6b6e62e-127c-4000-977a-5133ab4f03a6";
      fsType = "btrfs";
      options = [
        "subvol=@home"
        "compress=zstd:3" # 압축 수준 3 (성능과 압축률의 최적 지점)
        "noatime"         # 파일 읽을 때마다 시간을 기록하지 않음 (SSD 성능 향상)
        "discard=async"   # 백그라운드에서 TRIM 실행 (Linux 5.6+ 권장)
        "space_cache=v2"  # 최신 공간 캐시 알고리즘
      ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/a6b6e62e-127c-4000-977a-5133ab4f03a6";
      fsType = "btrfs";
      options = [
        "subvol=@nix"
        "compress=zstd:3" # 압축 수준 3 (성능과 압축률의 최적 지점)
        "noatime"         # 파일 읽을 때마다 시간을 기록하지 않음 (SSD 성능 향상)
        "discard=async"   # 백그라운드에서 TRIM 실행 (Linux 5.6+ 권장)
        "space_cache=v2"  # 최신 공간 캐시 알고리즘
      ];
    };

  fileSystems."/var/log" =
    { device = "/dev/disk/by-uuid/a6b6e62e-127c-4000-977a-5133ab4f03a6";
      fsType = "btrfs";
      options = [
        "subvol=@log"
        "compress=zstd:3" # 압축 수준 3 (성능과 압축률의 최적 지점)
        "noatime"         # 파일 읽을 때마다 시간을 기록하지 않음 (SSD 성능 향상)
        "discard=async"   # 백그라운드에서 TRIM 실행 (Linux 5.6+ 권장)
        "space_cache=v2"  # 최신 공간 캐시 알고리즘
      ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/C125-54BB";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  hardware.graphics.enable = true;
  hardware.graphics.enable32Bit = true;

  # 주기적인 Scrub (데이터 무결성 검사 및 복구)
  services = {
    btrfs.autoScrub = {
      enable = true;
      interval = "weekly";
      fileSystems = [ "/" ];
    };

    fstrim.enable = true;
  };

  hardware.bluetooth = {
    enable = true;
    powerOnBoot = true;
  };

  services.blueman.enable = true;
}
