system              = "x86_64-linux"
username            = "donghans"
rollingStateVersion = "26.05"
diskDevice          = "/dev/disk/by-label/nixos"
bootDevice          = "/dev/disk/by-label/boot"
# bootLoader        = "grub-uefi"   # 부트로더: "systemd-boot"(기본) | "grub-bios" | "grub-uefi"
nixCacheAddr        = ""            # Nix 캐시 프록시 서버 주소 (예: 192.168.1.10:7070). 비어있으면 미사용.
timeZone            = "Asia/Seoul"
defaultLocale       = "en_US.UTF-8"
extraLocale         = "ko_KR.UTF-8"

[git]
name     = "신동한"
email    = "78710114+donghans@users.noreply.github.com"
nixosRepo = "donghans/nixos"
