# Server Preset
# stateVersion 명시 → isRolling = false (서버는 stable nixpkgs 고정)
stateVersion = "25.11"
pkgsVersion = "25.11"

[mods.sys]
base = true
fonts = false
vfs = false

[mods.sys.utils]
nfd   = true
trash = true

[mods.sys.services]
tailscale      = false
incus          = false
incus-win11    = false
incus-guest    = false
caddy          = false
bluetooth        = false
docker           = false
nix-cache-proxy    = false
aws-roles-anywhere      = false
print-co                = false
tailpass                = false

[mods.gui]
enable = false

[mods.devel]
enable = false
