# Server Preset

[mods.sys]
base = true
fonts = false
vfs = false

[mods.sys.utils]
nfd   = true
trash = true

[mods.sys.services]
tailscale      = false
incus          = false
incus-win11    = false
incus-guest    = false
caddy          = false
bluetooth        = false
docker           = false
nix-cache-proxy    = false
aws-roles-anywhere = false

[mods.gui]
enable = false

[mods.devel]
enable = false
