type      = "server"
preset    = "server"
username  = "admin"

[[preauth-keys]]
user = "system"
name = "devserver"

[mods.sys.services]
incus                 = true
tailscale             = true
incus-tailscale-proxy = true
