# Server-Nix Preset

[mods.sys]
base = true
serverMode = true

[mods.sys.services]
networkmanager = true
tailscale      = true
incus          = true
headscale      = true
caddy          = true
cockpit        = true
frp            = true
