# Server Preset

[mods.sys]
base = true
server = true
fonts = true
vfs = true

[mods.sys.utils]
nfd = true

[mods.sys.services]
networkmanager = true
tailscale      = true
incus          = true
incus-win11    = false
incus-guest    = false
headscale      = false
caddy          = true
cockpit        = true
frp            = false
bluetooth        = false
docker           = false
nix-cache-proxy  = false

[mods.gui]
enable = false

[mods.devel]
enable = false
