# stateVersion 미지정 → isRolling = true (nixup이 rolling lock 사용)
# stateVersion = "25.11" 처럼 명시 → isRolling = false (호스트별 lock 사용)

[mods.sys]
base = true
server = false

[mods.sys.utils]
nfd = true

[mods.sys.services]
bluetooth      = true
networkmanager = true
tailscale      = true
docker         = true
incus          = false
headscale      = false
caddy          = false
cockpit        = false
frp            = false

[mods.gui]
enable = true

[mods.devel]
enable = true

[explicitOptional]
# gui/default.nix가 gui.enable 시 크로스-도메인으로 자동 활성화
paths = [
  "mods.sys.fonts.enable",
  "mods.sys.vfs.enable"
]
