# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  # 부트 로더 (rEFInd가 찾을 수 있도록 최소한으로 설정)
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;
  boot.loader.efi.efiSysMountPoint = "/boot";

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "uas" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];

  boot.kernelPackages = pkgs.linuxPackages;

  boot.kernelModules = [ "kvm-intel" "ec_sys" ];
  boot.kernelParams = [
    "pcie_aspm=force"                 # PCIe 전원 관리 강제
    "i915.enable_psr=1"               # Intel 패널 셀프 리프레시 활성화
    "i8042.nopnp"                     # PnP 기능이 문제를 일으킬 때 강제 비활성화
    "pci=nocms"                       # MSI 일부 모델에서 효과가 있는 PCI 설정
    "psmouse.synaptics_intertouch=0"  # Synaptics 패드일 경우 I2C 대신 PS/2 모드 강제
  ];
  boot.blacklistedKernelModules = [ "nouveau" "nvidia" "nvidia_drm" "nvidia_modeset" ];
  boot.extraModulePackages = [ ];

  boot.extraModprobeConfig = ''
    blacklist nouveau
    options nouveau modeset=0
    options ec_sys write_support=1
  '';


  fileSystems."/" =
    { device = "/dev/disk/by-uuid/1bd06feb-e860-4da4-ba07-80b98c7a0454";
      fsType = "btrfs";
      options = [
        "subvol=@"
        "compress=zstd:3" # 압축 수준 3 (성능과 압축률의 최적 지점)
        "noatime"         # 파일 읽을 때마다 시간을 기록하지 않음 (SSD 성능 향상)
        "discard=async"   # 백그라운드에서 TRIM 실행 (Linux 5.6+ 권장)
        "space_cache=v2"  # 최신 공간 캐시 알고리즘
      ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/1bd06feb-e860-4da4-ba07-80b98c7a0454";
      fsType = "btrfs";
      options = [
        "subvol=@home"
        "compress=zstd:3" # 압축 수준 3 (성능과 압축률의 최적 지점)
        "noatime"         # 파일 읽을 때마다 시간을 기록하지 않음 (SSD 성능 향상)
        "discard=async"   # 백그라운드에서 TRIM 실행 (Linux 5.6+ 권장)
        "space_cache=v2"  # 최신 공간 캐시 알고리즘
      ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/1bd06feb-e860-4da4-ba07-80b98c7a0454";
      fsType = "btrfs";
      options = [
        "subvol=@nix"
        "compress=zstd:3" # 압축 수준 3 (성능과 압축률의 최적 지점)
        "noatime"         # 파일 읽을 때마다 시간을 기록하지 않음 (SSD 성능 향상)
        "discard=async"   # 백그라운드에서 TRIM 실행 (Linux 5.6+ 권장)
        "space_cache=v2"  # 최신 공간 캐시 알고리즘
      ];
    };

  fileSystems."/var/log" =
    { device = "/dev/disk/by-uuid/1bd06feb-e860-4da4-ba07-80b98c7a0454";
      fsType = "btrfs";
      options = [
        "subvol=@log"
        "compress=zstd:3" # 압축 수준 3 (성능과 압축률의 최적 지점)
        "noatime"         # 파일 읽을 때마다 시간을 기록하지 않음 (SSD 성능 향상)
        "discard=async"   # 백그라운드에서 TRIM 실행 (Linux 5.6+ 권장)
        "space_cache=v2"  # 최신 공간 캐시 알고리즘
      ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/57B8-D582";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  hardware.graphics.enable = true;
  hardware.graphics.enable32Bit = true;

  # 주기적인 Scrub (데이터 무결성 검사 및 복구)
  services = {
    btrfs.autoScrub = {
      enable = true;
      interval = "weekly";
      fileSystems = [ "/" ];
    };

    fstrim.enable = true;
  };


  # 절전 설정 (발열 제어)
  powerManagement.powertop.enable = true;

  # NVIDIA Fine Grained Control(정밀 제어): GPU를 미사용중이므로 대기전력 자체를 없애버려 발열 제어
  hardware.nvidia.powerManagement.finegrained = true;

  services.tlp = {
    enable = true;

    settings = {
      # 배터리 사용 시 CPU 성능 제한
      CPU_SCALING_GOVERNOR_ON_BAT = "powersave";
      CPU_ENERGY_PERF_POLICY_ON_BAT = "power";
      CPU_MAX_PERF_ON_BAT = 50;

      # AC 연결 시 설정
      CPU_SCALING_GOVERNOR_ON_AC = "balanced"; # 혹은 powersave (발열 제어 우선 시)
      CPU_ENERGY_PERF_POLICY_ON_AC = "balance_performance";
      CPU_MAX_PERF_ON_AC = 100;

      # 터보 부스트 제어 (가장 중요!)
      # AC에서도 터보 부스트를 꺼버리면(0), 절대 뜨거워지지 않는 '선비' 같은 노트북이 됩니다.
      CPU_BOOST_ON_BAT = 0;
      CPU_BOOST_ON_AC = 0;

      # 인텔 하이브리드 아키텍처 최적화
      # (선택 사항) 가벼운 작업 시 E-코어 우선 사용 유도
      SCHED_POWERSAVE_ON_AC = 1;
      SCHED_POWERSAVE_ON_BAT = 1;

      # 하드디스크 및 장치 절전
      SATA_LINKPWR_ON_BAT = "med_power_with_dipm";
      USB_AUTOSUSPEND = 1;
      USB_EXCLUDE_PHONE = 1; # 폰 연결 시 충전 방해 금지 (선택)

      # 배터리 <=> AC 전환간 최적화가 풀리는 현상 방지
      RUNTIME_PM_ON_AC = "auto";
      RUNTIME_PM_ON_BAT = "auto";
    };
  };

  services.udev.extraRules = ''
    # 터치패드 전원 관리 강제 활성화 (자동 절전 방지)
    # ELAN0305:00 04F3:31FD Touchpad 장치에 대해 절전 기능을 끕니다.
    ACTION=="add", SUBSYSTEM=="i2c", ATTR{name}=="ELAN0305:00 04F3:31FD Touchpad", ATTR{power/control}="on"

    # 전원 어댑터 상태가 바뀔 때마다 (AC -> BAT, BAT -> AC) powertop 자동 최적화 실행
    SUBSYSTEM=="power_supply", ATTR{online}=="0", RUN+="${pkgs.powertop}/bin/powertop --auto-tune"
    SUBSYSTEM=="power_supply", ATTR{online}=="1", RUN+="${pkgs.powertop}/bin/powertop --auto-tune"
  '';

  hardware.bluetooth = {
    enable = true;
    powerOnBoot = true;
  };

  services.blueman.enable = true;


  environment.systemPackages = with pkgs; [
    intel-media-driver # 하드웨어 가속용
    libva-vdpau-driver
    libvdpau-va-gl
  ];
}
