# Node.js & Tooling Overlay
_final: prev: let
  # == Prisma & Node Wrapper Logic ==
  # Prisma 엔진을 현재 디렉토리에서 상위로 올라가며 찾는 쉘 스크립트
  # (참고: Nix ''...'' 문자열에서 ''$ 는 쉘 변수 $ 의 이스케이프 → 출력 시 $VAR 로 확장)
  prismaDetectionScript = ''
    curr="''$PWD"
    while [ "''$curr" != "/" ]; do
      engines_dir="''$curr/node_modules/@prisma/engines"
      if [ -d "''$engines_dir" ]; then
        export PRISMA_ENGINES_DIR="''$engines_dir"
        _lib=$(find "''$engines_dir" -name "libquery_engine-*.so.node" | head -n 1)
        [ -n "''$_lib" ] && export PRISMA_QUERY_ENGINE_LIBRARY="''$_lib"
        _bin=$(find "''$engines_dir" -maxdepth 1 -name "query-engine-*" ! -name "*.so*" ! -name "*.node" | head -n 1)
        [ -n "''$_bin" ] && export PRISMA_QUERY_ENGINE_BINARY="''$_bin"
        _schema=$(find "''$engines_dir" -maxdepth 1 -name "schema-engine-*" ! -name "*.so*" ! -name "*.node" | head -n 1)
        [ -n "''$_schema" ] && export PRISMA_SCHEMA_ENGINE_BINARY="''$_schema"
        break
      fi
      curr=$(dirname "''$curr")
    done
    unset _lib _bin _schema
  '';

  # (목적: Node 환경에 Prisma 탐색 및 PNPM 글로벌 최적화 변수 주입)
  wrapNode = pkg: binName: (prev.mkWrapper {
    inherit pkg binName;
    libs = with prev; [stdenv.cc.cc openssl];
    bins = with prev; [openssl findutils];
    run = prismaDetectionScript;
  });

  # (목적: npm 명령어를 pnpm으로 대리 실행하는 래퍼)
  # CMD_TYPE=lock  (install/add/remove 등): pnpm 설치 + package-lock.json 갱신
  # CMD_TYPE=ci    (ci): /tmp lockfile 없으면 package-lock.json import 후 frozen install
  # CMD_TYPE=other (run/test 등): exec pnpm 그대로 위임
  npmPnpmWrapper = prev.lib.hiPrio (prev.writeShellScriptBin "npm" ''
    export pnpm_config_pm_on_fail=ignore
    export pnpm_config_verify_deps_before_run=false
    export pnpm_config_dangerously_allow_all_builds=true

    CMD="''${1:-}"
    case "''$CMD" in
      install|i|add|remove|rm|uninstall|un|update|up|upgrade|link|unlink)
        CMD_TYPE=lock ;;
      ci)
        CMD_TYPE=ci ;;
      *)
        CMD_TYPE=other ;;
    esac

    if [ "''$CMD_TYPE" = "other" ]; then
      if [ ! -f "pnpm-workspace.yaml" ] && [ -f "package.json" ]; then
        WS_OTHER=$(node -e "
          try {
            const p = JSON.parse(require('fs').readFileSync('package.json','utf8'));
            const ws = p.workspaces;
            if (ws) {
              const pkgs = Array.isArray(ws) ? ws : (ws.packages || []);
              if (pkgs.length) process.stdout.write(
                \"# auto-generated by npm-pnpm-wrapper\npackages:\n\" +
                pkgs.map(pkg => \"  - '\" + pkg + \"'\").join(\"\n\") + \"\n\"
              );
            }
          } catch(e) {}
        " 2>/dev/null)
        if [ -n "''$WS_OTHER" ]; then
          printf '%s' "''$WS_OTHER" > "pnpm-workspace.yaml"
          trap 'rm -f "pnpm-workspace.yaml"' EXIT INT TERM
        fi
      fi
      pnpm "$@"
      exit $?
    fi

    # --- lock / ci 공통 준비 ---
    LOCK_HASH=$(printf '%s' "''$PWD" | md5sum | cut -c1-8)
    LOCK_DIR="/tmp/pnpm-locks/''$LOCK_HASH"
    WS_TMP="/tmp/pnpm-workspaces/''$LOCK_HASH/pnpm-workspace.yaml"
    mkdir -p "''$LOCK_DIR" "$(dirname "''$WS_TMP")"

    # pnpm-workspace.yaml: 우리가 생성한 경우에만 EXIT 시 삭제
    CREATED_WORKSPACE=0
    trap '[ "''$CREATED_WORKSPACE" = "1" ] && rm -f "pnpm-workspace.yaml"' EXIT INT TERM

    if [ -f "pnpm-workspace.yaml" ] && grep -q "# auto-generated by npm-pnpm-wrapper" "pnpm-workspace.yaml"; then
      CREATED_WORKSPACE=1
    elif [ ! -f "pnpm-workspace.yaml" ] && [ -f "package.json" ]; then
      WS_CONTENT=$(node -e "
        try {
          const p = JSON.parse(require('fs').readFileSync('package.json','utf8'));
          const ws = p.workspaces;
          if (ws) {
            const pkgs = Array.isArray(ws) ? ws : (ws.packages || []);
            if (pkgs.length) process.stdout.write(
              \"# auto-generated by npm-pnpm-wrapper\npackages:\n\" +
              pkgs.map(pkg => \"  - '\" + pkg + \"'\").join(\"\n\") + \"\n\"
            );
          }
        } catch(e) {}
      " 2>/dev/null)
      if [ -n "''$WS_CONTENT" ]; then
        printf '%s' "''$WS_CONTENT" > "pnpm-workspace.yaml"
        printf '%s' "''$WS_CONTENT" > "''$WS_TMP"
        CREATED_WORKSPACE=1
      fi
    fi

    # --- lock: 설치 + package-lock.json 갱신 ---
    if [ "''$CMD_TYPE" = "lock" ]; then
      # package-lock.json이 /tmp lockfile보다 최신이면 캐시 무효화 → import로 재동기화
      if [ -f "package-lock.json" ] && [ -f "''$LOCK_DIR/pnpm-lock.yaml" ]; then
        if [ "package-lock.json" -nt "''$LOCK_DIR/pnpm-lock.yaml" ]; then
          rm -f "''$LOCK_DIR/pnpm-lock.yaml"
        fi
      fi
      if [ ! -f "''$LOCK_DIR/pnpm-lock.yaml" ] && [ -f "package-lock.json" ]; then
        pnpm import 2>/dev/null
        [ -f "pnpm-lock.yaml" ] && mv "pnpm-lock.yaml" "''$LOCK_DIR/"
      fi

      pnpm --lockfile-dir="''$LOCK_DIR" --virtual-store-dir="''$PWD/node_modules/.pnpm" --prefer-frozen-lockfile "$@"
      PNPM_EXIT=$?

      GIT_DIR=$(git rev-parse --git-dir 2>/dev/null)
      if [ -n "''$GIT_DIR" ]; then
        EXCLUDE="''$GIT_DIR/info/exclude"
        mkdir -p "$(dirname "''$EXCLUDE")"
        grep -qxF 'pnpm-lock.yaml' "''$EXCLUDE" 2>/dev/null \
          || echo 'pnpm-lock.yaml' >> "''$EXCLUDE"
      fi

      if [ -f "package.json" ]; then
        ${prev.nodejs_24}/bin/npm install --package-lock-only --ignore-scripts 2>/dev/null || true
      fi

      exit $PNPM_EXIT
    fi

    # --- ci: /tmp lockfile 없으면 package-lock.json → import ---
    if [ ! -f "''$LOCK_DIR/pnpm-lock.yaml" ]; then
      if [ -f "package-lock.json" ]; then
        pnpm import 2>/dev/null
        [ -f "pnpm-lock.yaml" ] && mv "pnpm-lock.yaml" "''$LOCK_DIR/"
      fi
    fi

    pnpm install --frozen-lockfile --lockfile-dir="''$LOCK_DIR" --virtual-store-dir="''$PWD/node_modules/.pnpm"
    exit $?
  '');

  # (목적: yarn 명령어를 pnpm으로 대리 실행하는 호환성 래퍼)
  yarnPnpmWrapper = prev.writeShellScriptBin "yarn" ''
    if [ -f "yarn.lock" ]; then
      if [ -d ".git" ]; then
        EXCLUDE_FILE=".git/info/exclude"
        mkdir -p "$(dirname "$EXCLUDE_FILE")"
        for item in "pnpm-lock.yaml" "node_modules"; do
          if ! grep -q "$item" "$EXCLUDE_FILE" 2>/dev/null; then
            echo "$item" >> "$EXCLUDE_FILE"
          fi
        done
      fi

      if [ ! -f "pnpm-lock.yaml" ]; then
        echo "💡 [pnpm-wrapper] yarn.lock 감지: pnpm-lock.yaml을 생성합니다..."
        pnpm import
      fi

      echo "🚀 [pnpm-wrapper] pnpm을 통해 명령어를 실행합니다: $@"
      exec pnpm "$@"
    else
      exec pnpm "$@"
    fi
  '';
in {
  node-wrapped = wrapNode prev.nodejs_24 "node";
  pnpm-wrapped = wrapNode prev.pnpm "pnpm";
  pnpm-yarn-wrapper = yarnPnpmWrapper;
  pnpm-npm-wrapper = npmPnpmWrapper;
}
