# Node.js & Tooling Overlay
_final: prev: let
  # == Prisma & Node Wrapper Logic ==
  # Prisma 엔진을 현재 디렉토리에서 상위로 올라가며 찾는 쉘 스크립트
  # (참고: Nix ''...'' 문자열에서 ''$ 는 쉘 변수 $ 의 이스케이프 → 출력 시 $VAR 로 확장)
  prismaDetectionScript = ''
    curr="''$PWD"
    while [ "''$curr" != "/" ]; do
      engines_dir="''$curr/node_modules/@prisma/engines"
      if [ -d "''$engines_dir" ]; then
        export PRISMA_ENGINES_DIR="''$engines_dir"
        _lib=$(find "''$engines_dir" -name "libquery_engine-*.so.node" | head -n 1)
        [ -n "''$_lib" ] && export PRISMA_QUERY_ENGINE_LIBRARY="''$_lib"
        _bin=$(find "''$engines_dir" -maxdepth 1 -name "query-engine-*" ! -name "*.so*" ! -name "*.node" | head -n 1)
        [ -n "''$_bin" ] && export PRISMA_QUERY_ENGINE_BINARY="''$_bin"
        _schema=$(find "''$engines_dir" -maxdepth 1 -name "schema-engine-*" ! -name "*.so*" ! -name "*.node" | head -n 1)
        [ -n "''$_schema" ] && export PRISMA_SCHEMA_ENGINE_BINARY="''$_schema"
        break
      fi
      curr=$(dirname "''$curr")
    done
    unset _lib _bin _schema
  '';

  # (목적: Node 환경에 Prisma 탐색 및 PNPM 글로벌 최적화 변수 주입)
  wrapNode = pkg: binName: (prev.mkWrapper {
    inherit pkg binName;
    libs = with prev; [stdenv.cc.cc openssl];
    bins = with prev; [openssl findutils];
    run = prismaDetectionScript;
  });

  # (목적: npm 명령어를 pnpm으로 대리 실행하는 래퍼)
  # CMD_TYPE=lock  (install/add/remove 등): pnpm 설치 + package-lock.json 갱신
  # CMD_TYPE=ci    (ci): /tmp lockfile 없으면 package-lock.json import 후 frozen install
  # CMD_TYPE=other (run/test 등): exec pnpm 그대로 위임
  npmPnpmWrapper = prev.lib.hiPrio (prev.writeShellScriptBin "npm" ''
    export pnpm_config_pm_on_fail=ignore
    export pnpm_config_verify_deps_before_run=false
    export pnpm_config_dangerously_allow_all_builds=true
    export pnpm_config_confirmModulesPurge=false

    CMD="''${1:-}"
    case "''$CMD" in
      install|i|add|remove|rm|uninstall|un|update|up|upgrade|link|unlink)
        CMD_TYPE=lock ;;
      ci)
        CMD_TYPE=ci ;;
      *)
        CMD_TYPE=other ;;
    esac

    # --- workspace root 탐지: CWD → 상위 dir 순서로 workspaces 필드 있는 package.json 찾기 ---
    WS_ROOT="''$PWD"
    _wr="''$PWD"
    while [ "''$_wr" != "/" ]; do
      if [ -f "''$_wr/package.json" ] && grep -qE '"workspaces"[[:space:]]*:' "''$_wr/package.json" 2>/dev/null; then
        WS_ROOT="''$_wr"; break
      fi
      _wr=$(dirname "''$_wr")
    done
    unset _wr
    # IS_SUBPKG=1: CWD != WS_ROOT 이고 CWD 자체에 package.json 있음 (직접 workspace 패키지)
    IS_SUBPKG=0
    REL_PATH="."
    if [ "''$PWD" != "''$WS_ROOT" ] && [ -f "''$PWD/package.json" ]; then
      REL_PATH="''${PWD#''$WS_ROOT/}"
      IS_SUBPKG=1
    fi

    if [ "''$CMD_TYPE" = "other" ]; then
      # workspace yaml 생성 (IS_SUBPKG에 따라 경로 분기)
      if [ "''$IS_SUBPKG" = "1" ]; then
        if [ ! -f "''$WS_ROOT/pnpm-workspace.yaml" ]; then
          WS_OTHER=$(NPM_WRAPPER_PKG="''$WS_ROOT/package.json" node -e "
            try {
              const p = JSON.parse(require('fs').readFileSync(process.env.NPM_WRAPPER_PKG,'utf8'));
              const ws = p.workspaces;
              if (ws) {
                const pkgs = Array.isArray(ws) ? ws : (ws.packages || []);
                if (pkgs.length) process.stdout.write(
                  \"# auto-generated by npm-pnpm-wrapper\npackages:\n\" +
                  pkgs.map(pkg => \"  - '\" + pkg + \"'\").join(\"\n\") + \"\n\"
                );
              }
            } catch(e) {}
          " 2>/dev/null)
          if [ -n "''$WS_OTHER" ]; then
            printf '%s' "''$WS_OTHER" > "''$WS_ROOT/pnpm-workspace.yaml"
            trap 'rm -f "''$WS_ROOT/pnpm-workspace.yaml"' EXIT INT TERM
          fi
        fi
      else
        if [ ! -f "pnpm-workspace.yaml" ] && [ -f "package.json" ]; then
          WS_OTHER=$(node -e "
            try {
              const p = JSON.parse(require('fs').readFileSync('package.json','utf8'));
              const ws = p.workspaces;
              if (ws) {
                const pkgs = Array.isArray(ws) ? ws : (ws.packages || []);
                if (pkgs.length) process.stdout.write(
                  \"# auto-generated by npm-pnpm-wrapper\npackages:\n\" +
                  pkgs.map(pkg => \"  - '\" + pkg + \"'\").join(\"\n\") + \"\n\"
                );
              }
            } catch(e) {}
          " 2>/dev/null)
          if [ -n "''$WS_OTHER" ]; then
            printf '%s' "''$WS_OTHER" > "pnpm-workspace.yaml"
            trap 'rm -f "pnpm-workspace.yaml"' EXIT INT TERM
          fi
        fi
      fi

      # Translate npm workspace flags (-w/--workspace) → pnpm --filter <pkg> <cmd>
      # --filter must precede the subcommand (pnpm --filter X run test, NOT pnpm run test --filter X)
      PNPM_FILTERS=()
      PNPM_REST=()
      while [ $# -gt 0 ]; do
        case "''$1" in
          -w)
            if [ -d "./''$2" ]; then
              PNPM_FILTERS+=("--filter" "./''$2")
            else
              PNPM_FILTERS+=("--filter" "''$2")
            fi
            shift 2 ;;
          --workspace=*)
            _WS="''${1#--workspace=}"
            if [ -d "./''$_WS" ]; then
              PNPM_FILTERS+=("--filter" "./''$_WS")
            else
              PNPM_FILTERS+=("--filter" "''$_WS")
            fi
            shift ;;
          --workspace)
            if [ -d "./''$2" ]; then
              PNPM_FILTERS+=("--filter" "./''$2")
            else
              PNPM_FILTERS+=("--filter" "''$2")
            fi
            shift 2 ;;
          *)
            PNPM_REST+=("''$1"); shift ;;
        esac
      done

      # IS_SUBPKG=1이고 명시적 -w 없으면 현재 패키지를 implicit filter로 추가
      if [ "''$IS_SUBPKG" = "1" ] && [ "''${#PNPM_FILTERS[@]}" -eq 0 ]; then
        PNPM_FILTERS=("--filter" "./''$REL_PATH")
      fi

      if [ "''$IS_SUBPKG" = "1" ]; then
        (cd "''$WS_ROOT" && pnpm "''${PNPM_FILTERS[@]}" "''${PNPM_REST[@]}")
      else
        pnpm "''${PNPM_FILTERS[@]}" "''${PNPM_REST[@]}"
      fi
      exit $?
    fi

    # --- lock / ci 공통 준비 ---
    LOCK_HASH=$(printf '%s' "''$WS_ROOT" | md5sum | cut -c1-8)
    LOCK_DIR="''${XDG_CACHE_HOME:-''$HOME/.cache}/pnpm-locks/''$LOCK_HASH"
    WS_TMP="''${XDG_CACHE_HOME:-''$HOME/.cache}/pnpm-workspaces/''$LOCK_HASH/pnpm-workspace.yaml"
    mkdir -p "''$LOCK_DIR" "$(dirname "''$WS_TMP")"

    # pnpm-workspace.yaml: 우리가 생성한 경우에만 EXIT 시 삭제
    CREATED_WORKSPACE=0
    trap '[ "''$CREATED_WORKSPACE" = "1" ] && rm -f "''$WS_ROOT/pnpm-workspace.yaml"' EXIT INT TERM

    if [ -f "''$WS_ROOT/pnpm-workspace.yaml" ] && grep -q "# auto-generated by npm-pnpm-wrapper" "''$WS_ROOT/pnpm-workspace.yaml"; then
      CREATED_WORKSPACE=1
    elif [ ! -f "''$WS_ROOT/pnpm-workspace.yaml" ] && [ -f "''$WS_ROOT/package.json" ]; then
      WS_CONTENT=$(NPM_WRAPPER_PKG="''$WS_ROOT/package.json" node -e "
        try {
          const p = JSON.parse(require('fs').readFileSync(process.env.NPM_WRAPPER_PKG,'utf8'));
          const ws = p.workspaces;
          if (ws) {
            const pkgs = Array.isArray(ws) ? ws : (ws.packages || []);
            if (pkgs.length) process.stdout.write(
              \"# auto-generated by npm-pnpm-wrapper\npackages:\n\" +
              pkgs.map(pkg => \"  - '\" + pkg + \"'\").join(\"\n\") + \"\n\"
            );
          }
        } catch(e) {}
      " 2>/dev/null)
      if [ -n "''$WS_CONTENT" ]; then
        printf '%s' "''$WS_CONTENT" > "''$WS_ROOT/pnpm-workspace.yaml"
        printf '%s' "''$WS_CONTENT" > "''$WS_TMP"
        CREATED_WORKSPACE=1
      fi
    fi

    # --- lock: 설치 + package-lock.json 갱신 ---
    if [ "''$CMD_TYPE" = "lock" ]; then
      # package-lock.json이 캐시 lockfile보다 최신이면 캐시 무효화 → import로 재동기화
      if [ -f "''$WS_ROOT/package-lock.json" ] && [ -f "''$LOCK_DIR/pnpm-lock.yaml" ]; then
        if [ "''$WS_ROOT/package-lock.json" -nt "''$LOCK_DIR/pnpm-lock.yaml" ]; then
          rm -f "''$LOCK_DIR/pnpm-lock.yaml"
        fi
      fi
      # "link": true 항목이 있으면 pnpm import가 workspace 패키지를 레지스트리에서 찾으려 해서 실패
      HAS_WORKSPACE_LINKS=0
      grep -q '"link"[[:space:]]*:[[:space:]]*true' "''$WS_ROOT/package-lock.json" 2>/dev/null && HAS_WORKSPACE_LINKS=1
      if [ "''$HAS_WORKSPACE_LINKS" = "0" ] && [ ! -f "''$LOCK_DIR/pnpm-lock.yaml" ] && [ -f "''$WS_ROOT/package-lock.json" ]; then
        (cd "''$WS_ROOT" && pnpm import 2>/dev/null)
        [ -f "''$WS_ROOT/pnpm-lock.yaml" ] && mv "''$WS_ROOT/pnpm-lock.yaml" "''$LOCK_DIR/"
      fi

      shift  # CMD 제거 → $@ = flags + pkg names
      if [ "''$CMD" = "install" ] || [ "''$CMD" = "i" ]; then
        # non-flag arg 있으면 패키지 추가 → pnpm add, 없으면 pnpm install
        HAS_PKG=0
        for arg in "''$@"; do
          case "''$arg" in -*) ;; *) HAS_PKG=1; break ;; esac
        done
        if [ "''$HAS_PKG" = "1" ]; then
          cp "''$LOCK_DIR/pnpm-lock.yaml" "''$WS_ROOT/pnpm-lock.yaml" 2>/dev/null || true
          if [ "''$IS_SUBPKG" = "1" ]; then
            (cd "''$WS_ROOT" && pnpm --filter "./''$REL_PATH" add "''$@")
          else
            (cd "''$WS_ROOT" && pnpm add "''$@")
          fi
          PNPM_EXIT=$?
          [ -f "''$WS_ROOT/pnpm-lock.yaml" ] && mv "''$WS_ROOT/pnpm-lock.yaml" "''$LOCK_DIR/"
        else
          # workspace link("link": true) 항목이 있으면 --lockfile-dir 외부 경로에서
          # 상대경로 해석 불가 → WS_ROOT에 lockfile 생성 후 캐시로 이동
          if [ "''$HAS_WORKSPACE_LINKS" = "1" ]; then
            rm -f "''$LOCK_DIR/pnpm-lock.yaml"
            # pnpm v11에서 link-workspace-packages 제거됨 → "*" → "workspace:*" 임시 패치
            NPM_WS_ROOT="''$WS_ROOT" node -e "
              const fs = require('fs'), path = require('path');
              const wsRoot = process.env.NPM_WS_ROOT;
              try {
                const lock = JSON.parse(fs.readFileSync(path.join(wsRoot,'package-lock.json'),'utf8'));
                const wsNames = [];
                for (const [k,v] of Object.entries(lock.packages||{})) { if (v.link) wsNames.push(k.slice(13)); }
                if (!wsNames.length) process.exit(0);
                function walk(dir) {
                  let r = [];
                  try { for (const e of fs.readdirSync(dir,{withFileTypes:true})) {
                    if (['node_modules','src-tauri','.git'].includes(e.name)) continue;
                    const f = path.join(dir,e.name);
                    if (e.isDirectory()) r=r.concat(walk(f)); else if (e.name==='package.json') r.push(f);
                  }} catch {}
                  return r;
                }
                for (const pj of walk(wsRoot)) {
                  let c = fs.readFileSync(pj,'utf8'), orig = c;
                  for (const n of wsNames) { c = c.split('\"'+n+'\": \"*\"').join('\"'+n+'\": \"workspace:*\"'); }
                  if (c !== orig) { fs.writeFileSync(pj+'.npm-wrapper-bak', orig); fs.writeFileSync(pj,c); }
                }
              } catch {}
            " 2>/dev/null
            (cd "''$WS_ROOT" && pnpm install "''$@")
            PNPM_EXIT=$?
            # workspace:* 패치 복원
            NPM_WS_ROOT="''$WS_ROOT" node -e "
              const fs = require('fs'), path = require('path');
              const wsRoot = process.env.NPM_WS_ROOT;
              function walk(dir) {
                let r = [];
                try { for (const e of fs.readdirSync(dir,{withFileTypes:true})) {
                  if (['node_modules','src-tauri','.git'].includes(e.name)) continue;
                  const f = path.join(dir,e.name);
                  if (e.isDirectory()) r=r.concat(walk(f)); else if (e.name.endsWith('.npm-wrapper-bak')) r.push(f);
                }} catch {}
                return r;
              }
              for (const b of walk(wsRoot)) fs.renameSync(b, b.slice(0,-16));
            " 2>/dev/null
            [ -f "''$WS_ROOT/pnpm-lock.yaml" ] && mv "''$WS_ROOT/pnpm-lock.yaml" "''$LOCK_DIR/"
          else
            (cd "''$WS_ROOT" && pnpm --lockfile-dir="''$LOCK_DIR" install "''$@")
            PNPM_EXIT=$?
          fi
        fi
      else
        # add/remove/update/link/unlink: CMD가 pnpm 동사로 직접 사용
        cp "''$LOCK_DIR/pnpm-lock.yaml" "''$WS_ROOT/pnpm-lock.yaml" 2>/dev/null || true
        if [ "''$IS_SUBPKG" = "1" ]; then
          (cd "''$WS_ROOT" && pnpm --filter "./''$REL_PATH" "''$CMD" "''$@")
        else
          (cd "''$WS_ROOT" && pnpm "''$CMD" "''$@")
        fi
        PNPM_EXIT=$?
        [ -f "''$WS_ROOT/pnpm-lock.yaml" ] && mv "''$WS_ROOT/pnpm-lock.yaml" "''$LOCK_DIR/"
      fi

      GIT_DIR=$(git rev-parse --git-dir 2>/dev/null)
      if [ -n "''$GIT_DIR" ]; then
        EXCLUDE="''$GIT_DIR/info/exclude"
        mkdir -p "$(dirname "''$EXCLUDE")"
        grep -qxF 'pnpm-lock.yaml' "''$EXCLUDE" 2>/dev/null \
          || echo 'pnpm-lock.yaml' >> "''$EXCLUDE"
        grep -qxF 'pnpm-workspace.yaml' "''$EXCLUDE" 2>/dev/null \
          || echo 'pnpm-workspace.yaml' >> "''$EXCLUDE"
      fi

      if [ -f "''$WS_ROOT/package.json" ]; then
        LOCK_GEN_PWD="''$WS_ROOT"
        LOCK_TMP=$(mktemp -d)
        find "''$LOCK_GEN_PWD" -name "package.json" \
          ! -path "*/node_modules/*" ! -path "*/src-tauri/*" | \
        while IFS= read -r pj; do
          rel=$(echo "''$pj" | sed "s|^''$LOCK_GEN_PWD/||")
          target_dir=$(dirname "''$rel")
          mkdir -p "''$LOCK_TMP/''$target_dir"
          sed 's/"workspace:\([^"]*\)"/"\1"/g' "''$pj" > "''$LOCK_TMP/''$rel"
        done
        (cd "''$LOCK_TMP" && ${prev.nodejs_24}/bin/npm install \
          --package-lock-only --ignore-scripts --legacy-peer-deps 2>/dev/null) \
          && cp "''$LOCK_TMP/package-lock.json" "''$LOCK_GEN_PWD/" 2>/dev/null || true
        rm -rf "''$LOCK_TMP"
      fi

      exit $PNPM_EXIT
    fi

    # --- ci: 캐시 lockfile 없으면 package-lock.json → import ---
    if [ ! -f "''$LOCK_DIR/pnpm-lock.yaml" ]; then
      if [ -f "''$WS_ROOT/package-lock.json" ]; then
        (cd "''$WS_ROOT" && pnpm import 2>/dev/null)
        [ -f "''$WS_ROOT/pnpm-lock.yaml" ] && mv "''$WS_ROOT/pnpm-lock.yaml" "''$LOCK_DIR/"
      fi
    fi

    (cd "''$WS_ROOT" && pnpm install --frozen-lockfile --lockfile-dir="''$LOCK_DIR")
    exit $?
  '');

  # (목적: yarn 명령어를 pnpm으로 대리 실행하는 호환성 래퍼)
  yarnPnpmWrapper = prev.writeShellScriptBin "yarn" ''
    if [ -f "yarn.lock" ]; then
      if [ -d ".git" ]; then
        EXCLUDE_FILE=".git/info/exclude"
        mkdir -p "$(dirname "$EXCLUDE_FILE")"
        for item in "pnpm-lock.yaml" "node_modules"; do
          if ! grep -q "$item" "$EXCLUDE_FILE" 2>/dev/null; then
            echo "$item" >> "$EXCLUDE_FILE"
          fi
        done
      fi

      if [ ! -f "pnpm-lock.yaml" ]; then
        echo "💡 [pnpm-wrapper] yarn.lock 감지: pnpm-lock.yaml을 생성합니다..."
        pnpm import
      fi

      echo "🚀 [pnpm-wrapper] pnpm을 통해 명령어를 실행합니다: $@"
      exec pnpm "$@"
    else
      exec pnpm "$@"
    fi
  '';
in {
  node-wrapped = wrapNode prev.nodejs_24 "node";
  pnpm-wrapped = wrapNode prev.pnpm "pnpm";
  pnpm-yarn-wrapper = yarnPnpmWrapper;
  pnpm-npm-wrapper = npmPnpmWrapper;
}
