#!/usr/bin/env bash
# shellcheck disable=SC2153  # ENV_FILE 등 상위 스크립트(rnixstrap.sh)에서 정의된 변수
# rnixstrap.task-setup.sh — 파일 생성 + 설치 + 배포
# (공개키 추출 → TOML/nix 생성 → resolve → build → nixos-anywhere → deploy-rs)
#
# 변수 의존:
#   _HOSTNAME, _IP, _SSH_KEY, _SYSTEM, _BOOT_LOADER, _DISK_DEVICE, _SERVICES[]
#   _HOST_IS_NEW, _TOML_IP, _TOML_SSH_KEY
#   NIXOS_PATH, BUILD_DIR, JSON_DIR, SCRIPT_DIR, ENV_FILE
#
# 출력 변수:
#   _PUB_KEY — ssh-keygen -y로 추출한 공개키 (hosts/pubs/<hostname>.pub 저장)

# ── NixOS primary username 읽기 (호스트별 TOML 우선, 없으면 _base.toml) ──────
_read_nixos_user() {
    python3 - "$NIXOS_PATH/hosts/${_HOSTNAME}.toml" "$NIXOS_PATH/hosts/_base.toml" <<'EOF'
import sys, tomllib
host_path, base_path = sys.argv[1:3]
with open(host_path, "rb") as f:
    host = tomllib.load(f)
if "username" in host:
    print(host["username"])
else:
    with open(base_path, "rb") as f:
        base = tomllib.load(f)
    print(base.get("username", "root"))
EOF
}

# ── SSH 옵션 (bootstrap / post 이원화) ───────────────────────────────────────
# BOOTSTRAP: nixos-anywhere 이전 + wait_for_ssh 폴링 — 호스트 키 미등록 단계
# POST     : wait_for_ssh 완료(keyscan 등록) 이후 — known_hosts 검증 활성화
_SSH_OPTS_BOOTSTRAP=(
    -o StrictHostKeyChecking=no
    -o BatchMode=yes
    -o UserKnownHostsFile=/dev/null
    -o LogLevel=ERROR
)
_SSH_OPTS_POST=(
    -o StrictHostKeyChecking=yes
    -o BatchMode=yes
    -o UserKnownHostsFile="$HOME/.ssh/known_hosts"
    -o LogLevel=ERROR
)
# 초기값 = bootstrap. wait_for_ssh 완료 후 POST로 전환됨.
_SSH_OPTS=("${_SSH_OPTS_BOOTSTRAP[@]}")

# ── 1. 공개키 추출 → _PUB_KEY 변수에 저장 ────────────────────────────────────
extract_pub_key() {
    log_msg "Prep" "공개키 추출 중 (ssh-keygen -y)..."
    _PUB_KEY=$(ssh-keygen -y -f "$_SSH_KEY" 2>/dev/null)
    if [ -z "$_PUB_KEY" ]; then
        log_msg "Error" "공개키 추출 실패. 키 파일을 확인하세요: $_SSH_KEY"
        exit 1
    fi
    _PUB_KEY="$_PUB_KEY $_HOSTNAME"
    log_msg "Done" "공개키 추출 완료"
}

# ── 1.5. 공개키 파일 저장 → hosts/deploy/<hostname>.pub ──────────────────────
write_pub_key_file() {
    local deploy_dir="$NIXOS_PATH/hosts/deploy"
    mkdir -p "$deploy_dir"
    printf '%s\n' "$_PUB_KEY" > "$deploy_dir/${_HOSTNAME}.pub"
    log_msg "Done" "공개키 저장: hosts/deploy/${_HOSTNAME}.pub"
}

# ── 2. TOML 생성 ─────────────────────────────────────────────────────────────
generate_toml() {
    local toml_path="$NIXOS_PATH/hosts/${_HOSTNAME}.toml"
    local ts
    ts=$(date "+%Y-%m-%d %H:%M:%S")

    # 서비스 목록 — rnixstrap.sh의 _ALL_SERVICES에서 id(짝수 인덱스)만 추출
    local -a all_services=()
    for (( _i=0; _i<${#_ALL_SERVICES[@]}; _i+=2 )); do
        all_services+=("${_ALL_SERVICES[$_i]}")
    done

    # SSH로 원격 머신 RAM 감지
    local _ram_gb=""
    _ram_gb=$(ssh "${_SSH_OPTS[@]}" "root@$_IP" \
        "awk '/^MemTotal:/ {printf \"%d\", int((\$2 + 1048575) / 1048576)}' /proc/meminfo" 2>/dev/null || true)

    {
        printf '# Generated by rnixstrap — %s\n' "$ts"
        printf 'preset     = "server"\n'
        printf 'type       = "server"\n'
        printf 'system     = "%s"\n' "$_SYSTEM"
        [ -n "$_ram_gb" ] && printf 'ramGb      = %s\n' "$_ram_gb"
        printf 'swapGb     = 0\n'
        printf 'tmpfsSize  = "0"\n'
        printf 'diskDevice = "%s"\n' "$_DISK_DEVICE"
        printf 'bootDevice = "%s"\n' "$_DISK_DEVICE"
        printf 'bootLoader = "%s"\n' "$_BOOT_LOADER"
        printf '\n'
        printf '[deploy]\n'
        printf 'ip          = "%s"\n' "$_IP"
        printf 'sshKey      = "%s"\n' "${_SSH_KEY/#$HOME/~}"
        printf '\n'
        printf '[mods.sys.services]\n'
        for svc in "${all_services[@]}"; do
            local enabled=false
            for sel in "${_SERVICES[@]+"${_SERVICES[@]}"}"; do
                [ "$sel" = "$svc" ] && enabled=true && break
            done
            printf '%s = %s\n' "$svc" "$enabled"
        done
    } > "$toml_path"
    log_msg "Done" "TOML 생성: hosts/${_HOSTNAME}.toml"
}

# ── 3. NixHostConfiguration 스텁 생성 ────────────────────────────────────────
generate_nix_stub() {
    local nix_path="$NIXOS_PATH/hosts/${_HOSTNAME}.nix"
    # 이미 존재하면 덮어쓰지 않음 (재설치 시 사용자 편집 내용 보존)
    [ -f "$nix_path" ] && return

    local has_caddy=false
    for sel in "${_SERVICES[@]+"${_SERVICES[@]}"}"; do
        [ "$sel" = "caddy" ] && has_caddy=true
    done

    {
        printf '# %s 호스트 설정 (rnixstrap으로 생성)\n' "$_HOSTNAME"
        printf '# SSH 공개키는 hosts/pubs/%s.pub 에서 자동 로드됩니다.\n' "$_HOSTNAME"
        printf '{mkHostConfiguration, ...}:\n'
        printf 'mkHostConfiguration (_: {\n'
        printf '  os = {\n'

        if [ "$has_caddy" = true ]; then
            printf '    # == Caddy reverse proxy ==\n'
            printf '    services.caddy.extraConfig = '"''"'\n'
            printf '      YOUR_DOMAIN {\n'
            printf '        reverse_proxy * localhost:8080\n'
            printf '      }\n'
            printf '    '"'''"';\n'
        else
            printf '    # 서비스 설정을 여기에 추가하세요.\n'
        fi

        printf '  };\n'
        printf '})\n'
    } > "$nix_path"
    log_msg "Done" "NixHostConfiguration 스텁 생성: hosts/${_HOSTNAME}.nix"
}

# ── 3.5. TOML의 ip/sshKey 업데이트 (기존 호스트, 값 변경 시만) ───────────────
_update_toml_if_changed() {
    [ "$_IP" = "$_TOML_IP" ] && [ "${_SSH_KEY/#$HOME/~}" = "$_TOML_SSH_KEY" ] && return
    log_msg "Prep" "TOML 업데이트 중..."
    python3 - "$NIXOS_PATH/hosts/${_HOSTNAME}.toml" "$_IP" "${_SSH_KEY/#$HOME/~}" <<'EOF'
import sys, re
path, new_ip, new_key = sys.argv[1:]
with open(path) as f:
    text = f.read()
text = re.sub(r'(ip\s*=\s*)"[^"]*"', f'\\1"{new_ip}"', text)
text = re.sub(r'(sshKey\s*=\s*)"[^"]*"', f'\\1"{new_key}"', text)
with open(path, "w") as f:
    f.write(text)
EOF
    log_msg "Done" "TOML 업데이트 완료"
}

# ── 4. resolved.json + BUILD_DIR 동기화 ───────────────────────────────────────
run_resolve_and_prepare() {
    log_msg "Task" "빌드 환경 준비 중..."
    python3 -B "$SCRIPT_DIR/nixup.task-resolve.py" "$NIXOS_PATH" "$JSON_DIR" >/dev/null

    # prepare_build_dir는 lib-build.sh에서 source됨
    prepare_build_dir "$NIXOS_PATH" "$BUILD_DIR" "$ENV_FILE"
    log_msg "Done" "빌드 환경 준비 완료"
}

# ── 5. RAM 사전 감지 (review 출력 전 호출, 실패 시 _REMOTE_RAM_MB=-1 유지) ──────
_probe_ram() {
    local out
    out=$(ssh -i "$_SSH_KEY" "${_SSH_OPTS[@]}" -o ConnectTimeout=8 \
        "${_SSH_USER}@${_IP}" \
        "awk '/MemTotal/{print int(\$2/1024)}' /proc/meminfo" \
        2>/dev/null) || true
    [[ "$out" =~ ^[0-9]+$ ]] && _REMOTE_RAM_MB="$out" || true
}

# ── 5.5. SSH 연결 프로브 + 디스크·부트 자동 감지 ─────────────────────────────
probe_disk_and_boot() {
    log_msg "Prep" "원격 디스크·부트 타입 감지 중..."
    local remote_out
    remote_out=$(ssh -i "$_SSH_KEY" "${_SSH_OPTS[@]}" -o ConnectTimeout=10 \
        "${_SSH_USER}@${_IP}" \
        'test -d /sys/firmware/efi && echo uefi || echo bios; lsblk -dn -o NAME,TYPE 2>/dev/null | awk '"'"'$2=="disk" && $1!~/^zram/{print "/dev/"$1; exit}'"'"'' \
        2>/dev/null) || true

    if [ -z "$remote_out" ]; then
        log_msg "Warn" "원격 감지 실패 — 기존 값 유지 (disk=$_DISK_DEVICE, boot=$_BOOT_LOADER)"
        return
    fi

    local boot_raw disk_raw
    boot_raw=$(printf '%s' "$remote_out" | sed -n '1p')
    disk_raw=$(printf '%s' "$remote_out" | sed -n '2p')

    case "$boot_raw" in
        uefi) _BOOT_LOADER="grub-uefi" ;;
        bios) _BOOT_LOADER="grub-bios" ;;
    esac
    [ -n "$disk_raw" ] && _DISK_DEVICE="$disk_raw"

    log_msg "Done" "감지: diskDevice=$_DISK_DEVICE  bootLoader=$_BOOT_LOADER"
}

_update_toml_disk_boot_if_changed() {
    [ "$_DISK_DEVICE" = "$_TOML_DISK_DEVICE" ] && [ "$_BOOT_LOADER" = "$_TOML_BOOT_LOADER" ] && return
    log_msg "Prep" "TOML diskDevice/bootLoader 업데이트 중..."
    python3 - "$NIXOS_PATH/hosts/${_HOSTNAME}.toml" "$_DISK_DEVICE" "$_BOOT_LOADER" <<'EOF'
import sys, re
path, new_disk, new_boot = sys.argv[1:]
with open(path) as f:
    text = f.read()
text = re.sub(r'(diskDevice\s*=\s*)"[^"]*"', f'\\1"{new_disk}"', text)
text = re.sub(r'(bootDevice\s*=\s*)"[^"]*"', f'\\1"{new_disk}"', text)
text = re.sub(r'(bootLoader\s*=\s*)"[^"]*"', f'\\1"{new_boot}"', text)
with open(path, "w") as f:
    f.write(text)
EOF
    if [ "$_DISK_DEVICE" != "$_TOML_DISK_DEVICE" ]; then
        log_msg "Done" "diskDevice: $_TOML_DISK_DEVICE → $_DISK_DEVICE"
    fi
    if [ "$_BOOT_LOADER" != "$_TOML_BOOT_LOADER" ]; then
        log_msg "Done" "bootLoader: $_TOML_BOOT_LOADER → $_BOOT_LOADER"
    fi
}

probe_ssh() {
    log_msg "Prep" "SSH 연결 확인 중 (${_SSH_USER}@$_IP)..."
    if ! ssh -i "$_SSH_KEY" "${_SSH_OPTS[@]}" -o ConnectTimeout=15 \
             "${_SSH_USER}@${_IP}" true 2>/dev/null; then
        log_msg "Error" "SSH 연결 실패: ${_SSH_USER}@${_IP}"
        log_msg "Notice" "확인 사항:"
        log_msg "Notice" "  • 인스턴스가 실행 중인지 확인"
        log_msg "Notice" "  • 보안 그룹 / 방화벽에서 포트 22(SSH) 개방 여부"
        log_msg "Notice" "  • 키 파일 권한: chmod 600 \"$_SSH_KEY\""
        exit 1
    fi
    log_msg "Done" "SSH 연결 확인"
}

# ── 6. nixos-anywhere 초기 설치 ───────────────────────────────────────────────
run_nixos_anywhere() {
    log_msg "Notice" "nixos-anywhere 초기 설치 시작..."
    log_msg "Notice" "  → disko로 디스크 파티셔닝 후 NixOS를 설치합니다."

    # hardware.nix를 원격에서 생성 (타깃 머신의 hw config)
    # --generate-hardware-config: 타깃 머신에서 nixos-generate-config 실행 후 로컬에 저장
    # hosts/deploy/<hostname>.hardware.nix 에 저장 (flake에서 per-host 경로로 참조)
    mkdir -p "$BUILD_DIR/hosts/deploy"
    local hw_path="$BUILD_DIR/hosts/deploy/${_HOSTNAME}.hardware.nix"

    log_exec "n-aw" ">" "nixos-anywhere: $_HOSTNAME"
    NIX_SSHOPTS="-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=ERROR" \
    nix run "github:nix-community/nixos-anywhere" -- \
        --flake "path:${BUILD_DIR}#${_HOSTNAME}" \
        --generate-hardware-config nixos-generate-config "$hw_path" \
        -i "$_SSH_KEY" \
        "${_SSH_USER}@${_IP}"
    log_exec "n-aw" "<" "nixos-anywhere: $_HOSTNAME"

    # 생성된 hardware.nix를 소스 레포로 역복사 (이후 rnixup이 사용)
    mkdir -p "$NIXOS_PATH/hosts/deploy"
    cp "$hw_path" "$NIXOS_PATH/hosts/deploy/${_HOSTNAME}.hardware.nix"
    log_msg "Done" "hardware.nix 저장: hosts/deploy/${_HOSTNAME}.hardware.nix"
}

# ── 7. SSH known_hosts 기존 항목 제거 ────────────────────────────────────────
# 새 호스트 키 등록은 wait_for_ssh 내부에서 ssh-keyscan으로 처리
renew_host_key() {
    log_msg "Prep" "SSH known_hosts에서 기존 항목 제거 중..."
    ssh-keygen -R "$_IP" 2>/dev/null || true
    log_msg "Done" "기존 호스트 키 제거 완료"
}

# ── 8. SSH 응답 폴링 (재부팅 대기) + 호스트 키 등록 + POST opts 전환 ─────────
# $1: SSH 유저 (기본값: root — deploy-rs 경로는 kexec 환경이므로 root만 접속 가능)
wait_for_ssh() {
    local poll_user="${1:-root}"
    log_msg "Notice" "재부팅 대기 중... (최대 10분, 5초 간격 폴링)"
    local deadline start attempt=0
    start=$(date +%s)
    deadline=$(( start + 600 ))
    while true; do
        attempt=$((attempt + 1))
        if ssh -i "$_SSH_KEY" "${_SSH_OPTS_BOOTSTRAP[@]}" -o ConnectTimeout=5 \
               "${poll_user}@$_IP" true 2>/dev/null; then
            local elapsed=$(( $(date +%s) - start ))
            # SSH 응답 확인 → 새 호스트 키 등록 후 이후 연결은 known_hosts 검증으로 전환
            ssh-keyscan -T 10 "$_IP" >> "$HOME/.ssh/known_hosts" 2>/dev/null
            _SSH_OPTS=("${_SSH_OPTS_POST[@]}")
            log_msg "Done" "SSH 응답 확인 + 호스트 키 등록 (${elapsed}초 경과, ${attempt}번째 시도)"
            return
        fi
        if [ "$(date +%s)" -ge "$deadline" ]; then
            log_msg "Error" "재부팅 후 SSH 응답 없음 (10분 초과)"
            log_msg "Notice" "  • 인스턴스 콘솔에서 부팅 로그 확인"
            log_msg "Notice" "  • SSH 접속 가능해진 후: rnixup 으로 재시도"
            exit 1
        fi
        sleep 5
    done
}

# ── 9. deploy-rs 최종 배포 ────────────────────────────────────────────────────
run_deploy_rs() {
    log_msg "Task" "deploy-rs로 최종 closure 배포 중..."
    log_exec "d-rs" ">" "deploy-rs: $_HOSTNAME"
    nix run "github:serokell/deploy-rs" -- \
        --skip-checks \
        "path:${BUILD_DIR}#${_HOSTNAME}"
    log_exec "d-rs" "<" "deploy-rs: $_HOSTNAME"
    log_msg "Done" "초기 배포 완료: $_HOSTNAME → $_IP"
}

# ── standalone 호스트 파일 준비 (기존 toml/nix 유지, disk/boot + pubkey만 갱신) ─
_write_standalone_files() {
    probe_ssh
    probe_disk_and_boot
    _update_toml_disk_boot_if_changed
    extract_pub_key
    write_pub_key_file
}

# ── 레포 → 원격 서버 전송 ─────────────────────────────────────────────────────
# git archive: 커밋된 파일만 포함. hardware.nix는 미커밋이므로 별도 scp.
# .git은 전송하지 않음 — 레포 크기가 클 수 있고 (pack 파일 포함), finalize 단계에서
# git init + remote add로 설정한 뒤 gh auth login 후 git fetch --depth=1로 동기화.
# $1: SSH 유저 (기본값: root). root 아닐 경우 sudo 사용.
transfer_repo_to_remote() {
    local u="${1:-root}"
    local pfx; [ "$u" = "root" ] && pfx="" || pfx="sudo "
    log_msg "Task" "레포 전송 중 (/opt/nixos)..."
    git -C "$NIXOS_PATH" archive HEAD \
        | ssh -i "$_SSH_KEY" "${_SSH_OPTS[@]}" "${u}@${_IP}" \
              "${pfx}mkdir -p /opt/nixos && ${pfx}tar xf - -C /opt/nixos"
    # hardware.nix: scp는 sudo 미지원 → /tmp 경유 후 sudo mv
    scp -i "$_SSH_KEY" "${_SSH_OPTS[@]}" \
        "$NIXOS_PATH/hosts/deploy/${_HOSTNAME}.hardware.nix" \
        "${u}@${_IP}:/tmp/${_HOSTNAME}.hardware.nix"
    ssh -i "$_SSH_KEY" "${_SSH_OPTS[@]}" "${u}@${_IP}" \
        "${pfx}mkdir -p /opt/nixos/hosts/deploy && ${pfx}mv /tmp/${_HOSTNAME}.hardware.nix /opt/nixos/hosts/deploy/"
    # nixup이 일반 유저로 실행되므로 레포 소유권을 해당 유저로 변경
    [ "$u" != "root" ] && ssh -i "$_SSH_KEY" "${_SSH_OPTS[@]}" "${u}@${_IP}" \
        "sudo chown -R ${u}:users /opt/nixos"
    log_msg "Done" "레포 전송 완료"
}

# ── 원격 서버 .env 설정 ───────────────────────────────────────────────────────
# $1: SSH 유저 (기본값: root). root 아닐 경우 sudo 사용.
set_remote_env() {
    local u="${1:-root}"
    local pfx; [ "$u" = "root" ] && pfx="" || pfx="sudo "
    ssh -i "$_SSH_KEY" "${_SSH_OPTS[@]}" "${u}@${_IP}" \
        "${pfx}bash -c 'echo NIXUP_LAST_HOST=${_HOSTNAME} > /opt/nixos/.env'"
    log_msg "Done" "원격 .env: NIXUP_LAST_HOST=${_HOSTNAME}"
}

# ── 원격 서버에서 nixup os 실행 ───────────────────────────────────────────────
# $1: SSH 유저 (기본값: root).
# nixup.sh는 일반 유저로 실행하고 내부에서 sudo를 처리하므로 외부 sudo 불필요.
# standalone 서버는 wheelNeedsPassword=false이므로 nixup 내부 sudo -v가 비밀번호 없이 통과.
run_nixup_os_remote() {
    local u="${1:-root}"
    log_msg "Task" "원격 nixup os 실행 중..."
    log_exec "nixup" ">" "nixup os: $_HOSTNAME"
    local _exit=0
    ssh -i "$_SSH_KEY" "${_SSH_OPTS[@]}" "${u}@${_IP}" \
        "/opt/nixos/core/scripts/nixup.sh os" || _exit=$?
    log_exec "nixup" "<" "nixup os: $_HOSTNAME"
    if [ "$_exit" -eq 255 ]; then
        # switch-to-configuration switch가 sshd를 재시작하면 연결이 끊어짐 (정상)
        log_msg "Notice" "SSH 연결 끊어짐 — sshd 재시작으로 인한 것으로 보임. 재연결 대기..."
    elif [ "$_exit" -ne 0 ]; then
        log_msg "Error" "원격 nixup os 실패 (exit $_exit)"
        exit 1
    fi
    log_msg "Done" "원격 nixup os 완료"
}

# ── 레포를 홈 디렉터리로 이동 + /etc/nixos 심링크 (standalone 마무리) ─────────
# /opt/nixos/ → ~/nixos/  +  /etc/nixos → ~/nixos  +  chown
# nixstrap 로컬 설치와 동일한 구조로 맞춤
# git remote 설정: gh auth login 후 git fetch --depth=1 origin <branch> 로 동기화 가능
# $1: SSH 유저
finalize_standalone_repo() {
    local u="${1:-root}"
    local _origin _branch
    _origin=$(git -C "$NIXOS_PATH" remote get-url origin 2>/dev/null || true)
    _branch=$(git -C "$NIXOS_PATH" rev-parse --abbrev-ref HEAD 2>/dev/null || echo "main")
    log_msg "Task" "레포를 홈 디렉터리로 이동 중 (/opt/nixos → ~/nixos)..."
    ssh -i "$_SSH_KEY" "${_SSH_OPTS[@]}" "${u}@${_IP}" \
        "sudo bash -s -- '${u}' '${_origin}' '${_branch}'" <<'REMOTE'
NIXOS_USER="$1"
ORIGIN_URL="$2"
BRANCH="$3"
USER_HOME=$(getent passwd "$NIXOS_USER" | cut -d: -f6)
[ -z "$USER_HOME" ] && USER_HOME="/home/$NIXOS_USER"
mv /opt/nixos "$USER_HOME/nixos"
rm -rf /etc/nixos
ln -sfn "$USER_HOME/nixos" /etc/nixos
chown -R "$NIXOS_USER:users" "$USER_HOME/nixos"
# git remote 설정 (gh auth login 후 fetch 가능하도록)
if [ -n "$ORIGIN_URL" ]; then
    su -s /bin/sh -c "
        git -C ~/nixos init -q -b '$BRANCH' 2>/dev/null
        git -C ~/nixos remote add origin '$ORIGIN_URL' 2>/dev/null || true
    " "$NIXOS_USER"
fi
REMOTE
    log_msg "Done" "레포 이동 완료: ~/nixos, /etc/nixos 심링크"
    if [ -n "$_origin" ]; then
        log_msg "Notice" "git pull 설정: gh auth login 후 아래 명령 실행"
        log_msg "Notice" "  git -C ~/nixos fetch --depth=1 origin ${_branch}"
        log_msg "Notice" "  git -C ~/nixos reset --hard FETCH_HEAD"
        log_msg "Notice" "  git -C ~/nixos branch -u origin/${_branch} ${_branch}"
    fi
}

# ── bootstrap.env 저장 ────────────────────────────────────────────────────────
save_bootstrap_env() {
    local env_file="$HOME/.ssh/rnixup/${_HOSTNAME}.bootstrap.env"
    mkdir -p "$(dirname "$env_file")"
    chmod 700 "$(dirname "$env_file")"
    printf '_IP=%s\n_SSH_KEY=%s\n_SSH_USER=%s\n' \
        "$_IP" "${_SSH_KEY/#$HOME/~}" "$_SSH_USER" > "$env_file"
    chmod 600 "$env_file"
    log_msg "Done" "bootstrap.env 저장: ~/.ssh/rnixup/${_HOSTNAME}.bootstrap.env"
}

# ── 새 호스트 파일 생성 ───────────────────────────────────────────────────────
_write_new_host_files() {
    probe_ssh
    probe_disk_and_boot
    if [ -z "$_BOOT_LOADER" ]; then
        log_msg "Warn" "부트 타입 자동 감지 실패 — 수동 선택이 필요합니다."
        printf "\n"
        _pick "부트 타입 선택:" \
            "grub-bios  (MBR/GRUB, AWS Lightsail 등 구형 BIOS 전용)" \
            "grub-uefi  (GPT/GRUB+EFI, Hetzner/GCP 등 가상화 EFI)"
        _BOOT_LOADER="grub-bios"
        [ "$REPLY" -eq 1 ] && _BOOT_LOADER="grub-uefi"
        log_msg "Done" "부트 타입: $_BOOT_LOADER (수동 선택)"
    fi
    extract_pub_key
    write_pub_key_file
    generate_toml
    generate_nix_stub
}

# ── 설치 + 배포 (deploy-rs 모델) ─────────────────────────────────────────────
_run_install() {
    run_resolve_and_prepare
    run_nixos_anywhere
    renew_host_key
    wait_for_ssh
    run_deploy_rs
}

# ── 기본 SSH 키 생성 (gh auth login 첫 실행 EROFS 방지) ──────────────────────
# $1: SSH 유저. 키가 이미 있으면 건너뜀.
_ensure_default_ssh_key() {
    local u="${1:-root}"
    ssh -i "$_SSH_KEY" "${_SSH_OPTS[@]}" "${u}@${_IP}" \
        '[ -f ~/.ssh/id_ed25519 ] || ssh-keygen -t ed25519 -f ~/.ssh/id_ed25519 -N "" -q' 2>/dev/null || true
    log_msg "Done" "기본 SSH 키 준비 완료 (gh auth login용)"
}

# ── 설치 + 레포 전송 + 원격 nixup os (standalone 모델) ───────────────────────
# nixos-anywhere 이후 NixOS가 root SSH를 "no"로 설정하므로 primary user 사용
_run_install_standalone() {
    local _nixos_user
    _nixos_user=$(_read_nixos_user)
    run_resolve_and_prepare
    run_nixos_anywhere
    renew_host_key
    wait_for_ssh "$_nixos_user"
    transfer_repo_to_remote "$_nixos_user"
    set_remote_env "$_nixos_user"
    run_nixup_os_remote "$_nixos_user"
    wait_for_ssh "$_nixos_user"   # sshd 재시작 후 재연결 대기
    finalize_standalone_repo "$_nixos_user"
    _ensure_default_ssh_key "$_nixos_user"
}

# ── RAM 표시 라인 출력 헬퍼 ──────────────────────────────────────────────────
_print_ram_line() {
    if [ "$_REMOTE_RAM_MB" -eq -1 ]; then
        printf "  %-16s: \033[2m알 수 없음\033[0m\n" "RAM"
    elif [ "$_REMOTE_RAM_MB" -lt 1000 ]; then
        printf "  %-16s: \033[31m%sMB  ← 최소치(1000MB) 미달\033[0m\n" "RAM" "$_REMOTE_RAM_MB"
    elif [ "$_REMOTE_RAM_MB" -lt 1500 ]; then
        printf "  %-16s: \033[33m%sMB  ← kexec 실패 가능 (권장 1500MB)\033[0m\n" "RAM" "$_REMOTE_RAM_MB"
    else
        printf "  %-16s: %sMB\n" "RAM" "$_REMOTE_RAM_MB"
    fi
}

# ── 메인 오케스트레이터 ───────────────────────────────────────────────────────
run_setup() {
    # ── RAM 사전 감지 (review 전, 실패해도 무시) ──────────────────────────────
    _probe_ram

    # ── 설정 확인 출력 ────────────────────────────────────────────────────────
    printf "\n"
    if [ "${_HOST_IS_NEW:-true}" = true ]; then
        log_msg "Review" "설정 확인:"
        printf "  %-16s: %s\n" "hostname"   "$_HOSTNAME"
        printf "  %-16s: %s\n" "IP"         "$_IP"
        printf "  %-16s: %s\n" "SSH key"    "${_SSH_KEY/#$HOME/~}"
        printf "  %-16s: %s\n"              "system"     "$_SYSTEM"
        printf "  %-16s: \033[2m%s\033[0m\n" "diskDevice" "SSH 자동 감지"
        printf "  %-16s: \033[2m%s\033[0m\n" "bootLoader" "SSH 자동 감지"
        if [ ${#_SERVICES[@]} -gt 0 ]; then
            printf "  %-16s: %s\n" "services" "${_SERVICES[*]}"
        else
            printf "  %-16s: (없음)\n" "services"
        fi
        _print_ram_line
        printf "  %s\n" "────────────────────────────────────────────────"
        printf "  ${GREEN}%-42s %s${NC}\n" "hosts/${_HOSTNAME}.toml" "신규 생성"
        printf "  ${GREEN}%-42s %s${NC}\n" "hosts/${_HOSTNAME}.nix"  "신규 생성"
        printf "  \033[2m참고: 바로 진행/쓰기만 모두 SSH 접속 포함\033[0m\n"
    elif [ "${_HOST_HAS_DEPLOY:-true}" = false ]; then
        log_msg "Review" "설정 확인 (standalone bootstrap):"
        printf "  %-16s: %s\n" "hostname" "$_HOSTNAME"
        printf "  %-16s: %s\n" "IP"       "$_IP"
        printf "  %-16s: %s\n" "SSH key"  "${_SSH_KEY/#$HOME/~}"
        printf "  %-16s: %s  \033[2m(TOML)\033[0m\n"              "system"     "$_SYSTEM"
        printf "  %-16s: %s  \033[2m(TOML, 재감지 예정)\033[0m\n" "diskDevice" "$_DISK_DEVICE"
        printf "  %-16s: %s  \033[2m(TOML, 재감지 예정)\033[0m\n" "bootLoader" "$_BOOT_LOADER"
        _print_ram_line
        printf "  %s\n" "────────────────────────────────────────────────"
        printf "  \033[2m%-42s %s\033[0m\n" "hosts/${_HOSTNAME}.nix"  "유지"
        printf "  \033[2m%-42s %s\033[0m\n" "hosts/${_HOSTNAME}.toml" "disk/boot 재감지 후 업데이트"
        printf "  \033[2m참고: nixos-anywhere → 레포 전송 → 원격 nixup os\033[0m\n"
    else
        log_msg "Review" "설정 확인 (기존 호스트 재설치):"
        printf "  %-16s: %s\n" "hostname" "$_HOSTNAME"
        if [ "$_IP" != "$_TOML_IP" ]; then
            printf "  %-16s: \033[2m%s\033[0m  →  %s\n" "IP" "$_TOML_IP" "$_IP"
        else
            printf "  %-16s: %s\n" "IP" "$_IP"
        fi
        if [ "${_SSH_KEY/#$HOME/~}" != "$_TOML_SSH_KEY" ]; then
            printf "  %-16s: \033[2m%s\033[0m  →  %s\n" "SSH key" "$_TOML_SSH_KEY" "${_SSH_KEY/#$HOME/~}"
        else
            printf "  %-16s: %s\n" "SSH key" "${_SSH_KEY/#$HOME/~}"
        fi
        printf "  %-16s: %s  \033[2m(TOML)\033[0m\n"              "system"     "$_SYSTEM"
        printf "  %-16s: %s  \033[2m(TOML, 재감지 예정)\033[0m\n" "diskDevice" "$_DISK_DEVICE"
        printf "  %-16s: %s  \033[2m(TOML, 재감지 예정)\033[0m\n" "bootLoader" "$_BOOT_LOADER"
        _print_ram_line
        printf "  %s\n" "────────────────────────────────────────────────"
        printf "  \033[2m%-42s %s\033[0m\n" "hosts/${_HOSTNAME}.nix" "유지"
        if [ "$_IP" != "$_TOML_IP" ] || [ "${_SSH_KEY/#$HOME/~}" != "$_TOML_SSH_KEY" ]; then
            printf "  ${YELLOW}%-42s %s${NC}\n" "hosts/${_HOSTNAME}.toml" "업데이트 예정"
        else
            printf "  \033[2m%-42s %s\033[0m\n" "hosts/${_HOSTNAME}.toml" "변경 없음"
        fi
    fi
    printf "\n"

    # ── 선택 (RAM < 1000MB면 '바로 진행' 차단) ───────────────────────────────
    if [ "$_REMOTE_RAM_MB" -ne -1 ] && [ "$_REMOTE_RAM_MB" -lt 1000 ]; then
        printf "\n"
        log_msg "Error" "RAM ${_REMOTE_RAM_MB}MB — nixos-anywhere kexec 최소 1000MB 필요"
        log_msg "Notice" "  인스턴스를 더 높은 사양으로 업그레이드한 후 재시도하세요."
        printf "\n"
        _pick "다음 단계를 선택하세요:" \
            "쓰기만     — 파일 작업만 하고 종료 (설치 불가)" \
            "취소       — 아무것도 하지 않고 종료"
        [ "$REPLY" -eq 1 ] && { printf "\n"; log_msg "Notice" "취소되었습니다."; exit 0; }
        _WRITE_ONLY=true
    else
        [ "$_REMOTE_RAM_MB" -ne -1 ] && [ "$_REMOTE_RAM_MB" -lt 1500 ] && {
            printf "\n"
            log_msg "Warn" "RAM ${_REMOTE_RAM_MB}MB — kexec 실패 가능성 있음 (권장: 1500MB 이상)"
        }
        local _proceed_label
        if [ "${_HOST_HAS_DEPLOY:-true}" = false ]; then
            _proceed_label="바로 진행  — nixos-anywhere 설치 + 레포 전송 + nixup os"
        else
            _proceed_label="바로 진행  — nixos-anywhere 설치 + deploy-rs 배포"
        fi
        _pick "다음 단계를 선택하세요:" \
            "$_proceed_label" \
            "쓰기만     — 파일 작업만 하고 종료" \
            "취소       — 아무것도 하지 않고 종료"
        [ "$REPLY" -eq 2 ] && { printf "\n"; log_msg "Notice" "취소되었습니다."; exit 0; }
        [ "$REPLY" -eq 1 ] && _WRITE_ONLY=true || _WRITE_ONLY=false
    fi

    # 대화형 선택 완료 후부터 시간 측정
    _START_TIME=$(date +%s)
    _START_TIME_STR=$(date "+%Y-%m-%d %H:%M:%S")

    # ── 파일 작업 (바로 진행 + 쓰기만 공통) ──────────────────────────────────
    if [ "${_HOST_IS_NEW:-true}" = true ]; then
        _write_new_host_files
    elif [ "${_HOST_HAS_DEPLOY:-true}" = false ]; then
        : # standalone: 바로 진행 시 _write_standalone_files 호출 (아래에서 처리)
    else
        _update_toml_if_changed
    fi

    # ── 쓰기만 종료 ───────────────────────────────────────────────────────────
    if [ "$_WRITE_ONLY" = true ]; then
        printf "\n"
        if [ "${_HOST_IS_NEW:-true}" = true ]; then
            log_msg "Notice" "파일만 생성하고 종료합니다."
            log_msg "Notice" "  hosts/${_HOSTNAME}.nix 플레이스홀더를 실제 값으로 교체 후:"
            log_msg "Notice" "  rnixstrap 재실행 → '$_HOSTNAME' 선택 → 배포 재개"
        elif [ "${_HOST_HAS_DEPLOY:-true}" = false ]; then
            log_msg "Notice" "standalone 모드: 파일 작업 없이 종료합니다."
            log_msg "Notice" "  rnixstrap 재실행 → '$_HOSTNAME' 선택 → bootstrap 재개"
        else
            if [ "$_IP" != "$_TOML_IP" ] || [ "${_SSH_KEY/#$HOME/~}" != "$_TOML_SSH_KEY" ]; then
                log_msg "Notice" "TOML 업데이트 완료하고 종료합니다."
            else
                log_msg "Notice" "변경 사항 없음. 종료합니다."
            fi
        fi
        exit 0
    fi

    # ── 바로 진행 ─────────────────────────────────────────────────────────────
    if [ "${_HOST_HAS_DEPLOY:-true}" = false ]; then
        # standalone bootstrap: probe + pub key + nixos-anywhere + 레포 전송 + nixup os
        _write_standalone_files
        _run_install_standalone
        save_bootstrap_env
    else
        # deploy-rs 모델: 새 호스트 or 기존 호스트 재설치
        if [ "${_HOST_IS_NEW:-true}" != true ]; then
            probe_ssh
            probe_disk_and_boot
            _update_toml_disk_boot_if_changed
            extract_pub_key
            write_pub_key_file
        fi
        _run_install
    fi

    printf "\n"
    log_msg "Done" "════════════════════════════════════════"
    log_msg "Done" " $_HOSTNAME 초기 설치 + 배포 완료!"
    log_msg "Done" " IP: $_IP"
    log_msg "Done" "════════════════════════════════════════"
    printf "\n"
    log_msg "Notice" "다음 단계:"
    if [ "${_HOST_HAS_DEPLOY:-true}" = false ]; then
        log_msg "Notice" "  시크릿 주입 후 서비스 활성화:"
        log_msg "Notice" "    scp intermediate_ca.key root@$_IP:/var/lib/step-ca-secrets/"
        log_msg "Notice" "    scp password            root@$_IP:/var/lib/step-ca-secrets/password"
        log_msg "Notice" "    ssh root@$_IP /opt/nixos/core/scripts/nixup.sh os"
    elif [ "${_HOST_IS_NEW:-true}" = true ]; then
        log_msg "Notice" "  1. hosts/${_HOSTNAME}.nix 에서 플레이스홀더를 실제 값으로 교체"
        log_msg "Notice" "  2. rnixup 으로 설정 반영"
    else
        log_msg "Notice" "  rnixup 으로 이후 설정 변경을 배포하세요."
    fi
}
