#!/usr/bin/env bash
# rnixstrap.task-setup.sh — 파일 생성 + 설치 + 배포
# (공개키 추출 → TOML/nix 생성 → resolve → build → nixos-anywhere → deploy-rs)
#
# 변수 의존:
#   _HOSTNAME, _IP, _SSH_KEY, _SYSTEM, _BOOT_TARGET, _DISK_DEVICE, _SERVICES[]
#   _HOST_IS_NEW, _TOML_IP, _TOML_SSH_KEY
#   NIXOS_PATH, BUILD_DIR, JSON_DIR, SCRIPT_DIR, ENV_FILE
#
# 출력 변수:
#   _PUB_KEY — ssh-keygen -y로 추출한 공개키 (host.nix에 인라인 embed)

# ── 1. 공개키 추출 → _PUB_KEY 변수에 저장 ────────────────────────────────────
extract_pub_key() {
    log_msg "Prep" "공개키 추출 중 (ssh-keygen -y)..."
    _PUB_KEY=$(ssh-keygen -y -f "$_SSH_KEY" 2>/dev/null)
    if [ -z "$_PUB_KEY" ]; then
        log_msg "Error" "공개키 추출 실패. 키 파일을 확인하세요: $_SSH_KEY"
        exit 1
    fi
    _PUB_KEY="$_PUB_KEY $_HOSTNAME"
    log_msg "Done" "공개키 추출 완료"
}

# ── 2. TOML 생성 ─────────────────────────────────────────────────────────────
generate_toml() {
    local toml_path="$NIXOS_PATH/hosts/${_HOSTNAME}.toml"
    local ts
    ts=$(date "+%Y-%m-%d %H:%M:%S")

    # 서비스 목록 (server 프리셋 기준 전체 목록)
    local all_services=("caddy" "tailscale" "docker" "nix-cache-proxy")

    {
        printf '# Generated by rnixstrap — %s\n' "$ts"
        printf 'preset     = "server"\n'
        printf 'type       = "server"\n'
        printf 'system     = "%s"\n' "$_SYSTEM"
        printf 'swapGb     = 0\n'
        printf 'tmpfsSize  = "0"\n'
        printf 'diskDevice = "%s"\n' "$_DISK_DEVICE"
        printf 'bootDevice = "%s"\n' "$_DISK_DEVICE"
        printf '\n'
        printf '[deploy]\n'
        printf 'destination = "%s"\n' "$_BOOT_TARGET"
        printf 'ip          = "%s"\n' "$_IP"
        printf 'sshKey      = "%s"\n' "$_SSH_KEY"
        printf '\n'
        printf '[mods.sys.services]\n'
        for svc in "${all_services[@]}"; do
            local enabled=false
            for sel in "${_SERVICES[@]+"${_SERVICES[@]}"}"; do
                [ "$sel" = "$svc" ] && enabled=true && break
            done
            printf '%s = %s\n' "$svc" "$enabled"
        done
    } > "$toml_path"
    log_msg "Done" "TOML 생성: hosts/${_HOSTNAME}.toml"
}

# ── 3. NixHostConfiguration 스텁 생성 ────────────────────────────────────────
generate_nix_stub() {
    local nix_path="$NIXOS_PATH/hosts/${_HOSTNAME}.nix"

    # 선택된 서비스에 따라 추가 설정 결정
    local has_caddy=false
    for sel in "${_SERVICES[@]+"${_SERVICES[@]}"}"; do
        [ "$sel" = "caddy" ] && has_caddy=true
    done

    {
        printf '# %s 호스트 설정 (rnixstrap으로 생성)\n' "$_HOSTNAME"
        printf '# 배포 전 플레이스홀더를 실제 값으로 교체하세요.\n'
        printf '{mkHostConfiguration, ...}:\n'
        printf 'mkHostConfiguration (_: {\n'
        printf '  os = {\n'
        printf '    # == SSH 공개키 (nixos-anywhere 후 authorized_keys 재주입) ==\n'
        printf '    users.users.root.openssh.authorizedKeys.keys = [\n'
        printf '      "%s"\n' "$_PUB_KEY"
        printf '    ];\n'

        if [ "$has_caddy" = true ]; then
            printf '\n'
            printf '    # == Caddy reverse proxy ==\n'
            printf '    services.caddy.extraConfig = '"''"'\n'
            printf '      YOUR_DOMAIN {\n'
            printf '        reverse_proxy * localhost:8080\n'
            printf '      }\n'
            printf '    '"'''"';\n'
        fi

        printf '  };\n'
        printf '})\n'
    } > "$nix_path"
    log_msg "Done" "NixHostConfiguration 스텁 생성: hosts/${_HOSTNAME}.nix"
}

# ── 3.5. TOML의 ip/sshKey 업데이트 (기존 호스트, 값 변경 시만) ───────────────
_update_toml_if_changed() {
    [ "$_IP" = "$_TOML_IP" ] && [ "$_SSH_KEY" = "$_TOML_SSH_KEY" ] && return
    log_msg "Prep" "TOML 업데이트 중 (ip/sshKey 변경됨)..."
    python3 - "$NIXOS_PATH/hosts/${_HOSTNAME}.toml" "$_IP" "$_SSH_KEY" <<'EOF'
import sys, re
path, new_ip, new_key = sys.argv[1], sys.argv[2], sys.argv[3]
with open(path) as f:
    text = f.read()
text = re.sub(r'(ip\s*=\s*)"[^"]*"', f'\\1"{new_ip}"', text)
text = re.sub(r'(sshKey\s*=\s*)"[^"]*"', f'\\1"{new_key}"', text)
with open(path, "w") as f:
    f.write(text)
EOF
    log_msg "Done" "TOML 업데이트 완료 (ip/sshKey)"
}

# ── 4. resolved.json + BUILD_DIR 동기화 ───────────────────────────────────────
run_resolve_and_prepare() {
    log_msg "Task" "빌드 환경 준비 중..."
    python3 -B "$SCRIPT_DIR/nixup.task-resolve.py" "$NIXOS_PATH" "$JSON_DIR" >/dev/null

    # prepare_build_dir는 nixup.lib-build.sh에서 source됨
    prepare_build_dir "$NIXOS_PATH" "$BUILD_DIR" "$ENV_FILE"
    log_msg "Done" "빌드 환경 준비 완료"
}

# ── 5. SSH 연결 프로브 ────────────────────────────────────────────────────────
probe_ssh() {
    log_msg "Prep" "SSH 연결 확인 중 (root@$_IP)..."
    if ! ssh -i "$_SSH_KEY" \
             -o ConnectTimeout=15 \
             -o StrictHostKeyChecking=no \
             -o BatchMode=yes \
             "root@$_IP" true 2>/dev/null; then
        log_msg "Error" "SSH 연결 실패: root@$_IP"
        log_msg "Notice" "확인 사항:"
        log_msg "Notice" "  • 인스턴스가 실행 중인지 확인"
        log_msg "Notice" "  • 보안 그룹 / 방화벽에서 포트 22(SSH) 개방 여부"
        log_msg "Notice" "  • 키 파일 권한: chmod 600 \"$_SSH_KEY\""
        exit 1
    fi
    log_msg "Done" "SSH 연결 확인"
}

# ── 6. nixos-anywhere 초기 설치 ───────────────────────────────────────────────
run_nixos_anywhere() {
    log_msg "Notice" "nixos-anywhere 초기 설치 시작..."
    log_msg "Notice" "  → disko로 디스크 파티셔닝 후 NixOS를 설치합니다."

    # hardware.nix를 원격에서 생성 (local 머신의 hw config가 아닌 타깃 머신의 hw config)
    # --generate-hardware-config: 타깃 머신에서 nixos-generate-config 실행 후 로컬에 저장
    local hw_path="$BUILD_DIR/hardware.nix"

    log_exec "nixos-anywhere" ">" "initial install ($_HOSTNAME)"
    nix run "github:nix-community/nixos-anywhere" -- \
        --flake "path:${BUILD_DIR}#${_HOSTNAME}" \
        --generate-hardware-config nixos-generate-config "$hw_path" \
        -i "$_SSH_KEY" \
        "root@${_IP}"
    log_exec "nixos-anywhere" "<" "initial install ($_HOSTNAME)"
}

# ── 7. SSH known_hosts 갱신 ──────────────────────────────────────────────────
renew_host_key() {
    log_msg "Prep" "SSH known_hosts에서 기존 항목 제거 중..."
    ssh-keygen -R "$_IP" 2>/dev/null || true
    log_msg "Done" "호스트 키 갱신 완료"
}

# ── 8. SSH 응답 폴링 (재부팅 대기) ───────────────────────────────────────────
wait_for_ssh() {
    log_msg "Notice" "재부팅 대기 중... (최대 3분, 5초 간격 폴링)"
    local deadline attempt=0
    deadline=$(( $(date +%s) + 180 ))
    while true; do
        attempt=$((attempt + 1))
        if ssh -i "$_SSH_KEY" \
               -o ConnectTimeout=5 \
               -o StrictHostKeyChecking=no \
               -o BatchMode=yes \
               "root@$_IP" true 2>/dev/null; then
            log_msg "Done" "SSH 응답 확인 (${attempt}번째 시도)"
            return
        fi
        if [ "$(date +%s)" -ge "$deadline" ]; then
            log_msg "Error" "재부팅 후 SSH 응답 없음 (3분 초과)"
            log_msg "Notice" "  • 인스턴스 콘솔에서 부팅 로그 확인"
            log_msg "Notice" "  • SSH 접속 가능해진 후: rnixup 으로 재시도"
            exit 1
        fi
        sleep 5
    done
}

# ── 9. deploy-rs 최종 배포 ────────────────────────────────────────────────────
run_deploy_rs() {
    log_msg "Task" "deploy-rs로 최종 closure 배포 중..."
    log_exec "deploy-rs" ">" "initial deploy $_HOSTNAME"
    nix run "github:serokell/deploy-rs" -- \
        --skip-checks \
        "path:${BUILD_DIR}#${_HOSTNAME}"
    log_exec "deploy-rs" "<" "initial deploy $_HOSTNAME"
    log_msg "Done" "초기 배포 완료: $_HOSTNAME → $_IP"
}

# ── 새 호스트 파일 생성 ───────────────────────────────────────────────────────
_write_new_host_files() {
    probe_ssh
    extract_pub_key
    generate_toml
    generate_nix_stub
}

# ── 설치 + 배포 ───────────────────────────────────────────────────────────────
_run_install() {
    run_resolve_and_prepare
    run_nixos_anywhere
    renew_host_key
    wait_for_ssh
    run_deploy_rs
}

# ── 메인 오케스트레이터 ───────────────────────────────────────────────────────
run_setup() {
    # ── 설정 확인 출력 ────────────────────────────────────────────────────────
    printf "\n"
    if [ "${_HOST_IS_NEW:-true}" = true ]; then
        printf "${CYAN}RNIXSTRAP${NC} ${CYAN}%-9s${NC} | 설정 확인:\n" "Review"
        printf "  %-16s: %s\n" "hostname"   "$_HOSTNAME"
        printf "  %-16s: %s\n" "provider"   "$_PROVIDER"
        printf "  %-16s: %s\n" "IP"         "$_IP"
        printf "  %-16s: %s\n" "SSH key"    "$_SSH_KEY"
        printf "  %-16s: %s\n" "system"     "$_SYSTEM"
        printf "  %-16s: %s\n" "bootTarget" "$_BOOT_TARGET"
        printf "  %-16s: %s\n" "diskDevice" "$_DISK_DEVICE"
        if [ ${#_SERVICES[@]} -gt 0 ]; then
            printf "  %-16s: %s\n" "services" "${_SERVICES[*]}"
        else
            printf "  %-16s: (없음)\n" "services"
        fi
        printf "  %s\n" "────────────────────────────────────────────────"
        printf "  ${GREEN}%-42s %s${NC}\n" "hosts/${_HOSTNAME}.toml" "신규 생성"
        printf "  ${GREEN}%-42s %s${NC}\n" "hosts/${_HOSTNAME}.nix"  "신규 생성"
        printf "  \033[2m참고: 바로 진행/쓰기만 모두 SSH 접속 포함\033[0m\n"
    else
        printf "${CYAN}RNIXSTRAP${NC} ${CYAN}%-9s${NC} | 설정 확인 \033[2m(기존 호스트 재설치)\033[0m:\n" "Review"
        printf "  %-16s: %s\n" "hostname" "$_HOSTNAME"
        if [ "$_IP" != "$_TOML_IP" ]; then
            printf "  %-16s: \033[2m%s\033[0m  →  %s\n" "IP" "$_TOML_IP" "$_IP"
        else
            printf "  %-16s: %s\n" "IP" "$_IP"
        fi
        if [ "$_SSH_KEY" != "$_TOML_SSH_KEY" ]; then
            printf "  %-16s: \033[2m%s\033[0m  →  %s\n" "SSH key" "$_TOML_SSH_KEY" "$_SSH_KEY"
        else
            printf "  %-16s: %s\n" "SSH key" "$_SSH_KEY"
        fi
        printf "  %-16s: %s  \033[2m(TOML)\033[0m\n" "system"     "$_SYSTEM"
        printf "  %-16s: %s  \033[2m(TOML)\033[0m\n" "bootTarget" "$_BOOT_TARGET"
        printf "  %-16s: %s  \033[2m(TOML)\033[0m\n" "diskDevice" "$_DISK_DEVICE"
        printf "  %s\n" "────────────────────────────────────────────────"
        printf "  \033[2m%-42s %s\033[0m\n" "hosts/${_HOSTNAME}.nix" "유지"
        if [ "$_IP" != "$_TOML_IP" ] || [ "$_SSH_KEY" != "$_TOML_SSH_KEY" ]; then
            printf "  ${YELLOW}%-42s %s${NC}\n" "hosts/${_HOSTNAME}.toml" "업데이트 예정"
        else
            printf "  \033[2m%-42s %s\033[0m\n" "hosts/${_HOSTNAME}.toml" "변경 없음"
        fi
    fi
    printf "\n"

    # ── 3-way 선택 ────────────────────────────────────────────────────────────
    _pick "다음 단계를 선택하세요:" \
        "바로 진행  — nixos-anywhere 설치 + deploy-rs 배포" \
        "쓰기만     — 파일 작업만 하고 종료" \
        "취소       — 아무것도 하지 않고 종료"

    # ── 취소 ──────────────────────────────────────────────────────────────────
    if [ "$REPLY" -eq 2 ]; then
        printf "\n"
        log_msg "Notice" "취소되었습니다."
        exit 0
    fi

    # ── 파일 작업 (바로 진행 + 쓰기만 공통) ──────────────────────────────────
    if [ "${_HOST_IS_NEW:-true}" = true ]; then
        _write_new_host_files
    else
        _update_toml_if_changed
    fi

    # ── 쓰기만 종료 ───────────────────────────────────────────────────────────
    if [ "$REPLY" -eq 1 ]; then
        printf "\n"
        if [ "${_HOST_IS_NEW:-true}" = true ]; then
            log_msg "Notice" "파일만 생성하고 종료합니다."
            log_msg "Notice" "  hosts/${_HOSTNAME}.nix 플레이스홀더를 실제 값으로 교체 후:"
            log_msg "Notice" "  rnixstrap 재실행 → '$_HOSTNAME' 선택 → 배포 재개"
        else
            if [ "$_IP" != "$_TOML_IP" ] || [ "$_SSH_KEY" != "$_TOML_SSH_KEY" ]; then
                log_msg "Notice" "TOML 업데이트 완료하고 종료합니다."
            else
                log_msg "Notice" "변경 사항 없음. 종료합니다."
            fi
        fi
        exit 0
    fi

    # ── 바로 진행: 기존 호스트는 SSH probe 추가 후 설치 ──────────────────────
    if [ "${_HOST_IS_NEW:-true}" != true ]; then
        probe_ssh
    fi
    _run_install

    printf "\n"
    log_msg "Done" "════════════════════════════════════════"
    log_msg "Done" " $_HOSTNAME 초기 설치 + 배포 완료!"
    log_msg "Done" " IP: $_IP"
    log_msg "Done" "════════════════════════════════════════"
    printf "\n"
    log_msg "Notice" "다음 단계:"
    if [ "${_HOST_IS_NEW:-true}" = true ]; then
        log_msg "Notice" "  1. hosts/${_HOSTNAME}.nix 에서 플레이스홀더를 실제 값으로 교체"
        log_msg "Notice" "  2. rnixup 으로 설정 반영"
    else
        log_msg "Notice" "  rnixup 으로 이후 설정 변경을 배포하세요."
    fi
}
